server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersystem
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

keycloak:
  realm: ordersystem
  auth-server-url: http://localhost:8081/auth
  resource: ordersystem-client
  public-client: true
  bearer-only: true 